# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Lily58M'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["lily58_left","lily58_right"]'
      snippet: '["zmk-usb-logging"]'
